
---
- hosts: localhost
  vars_files: 
      - secure.yml
        
  tasks: 
  - name: launching lb-server
    ec2:
      key_name: mykey11
      instance_type: t2.micro
      region: ap-south-1
      image: ami-0a9d27a9f4f5c0efc
      vpc_subnet_id: subnet-03a951776444f8ab7
      wait: yes
      count: 1
      instance_tags:
           name: lb
      assign_public_ip: yes
      aws_access_key: "{{ access_kay }}"
      aws_secret_key: "{{ secret_key }}"
      group_id: sg-0040e7dcb8558adf4
    register: lbb
   

    
  - name: launching web-servers
    ec2:
      key_name: mykey11
      instance_type: t2.micro
      region: ap-south-1
      image: ami-0a9d27a9f4f5c0efc
      vpc_subnet_id: subnet-03a951776444f8ab7
      wait: yes
      count: 2
      instance_tags:
           name: web
      assign_public_ip: yes
      aws_access_key: "{{ access_kay }}"
      aws_secret_key: "{{ secret_key }}"
      group_id: sg-0040e7dcb8558adf4
    register: webb

  - meta: refresh_inventory

  - name: adding hostnames
    add_host: 
         hostname: "{{ item.public_ip }}"
         groups: web
    loop: "{{ webb.instances }}"

  - name: wait for ssh
    wait_for:
            host: "{{ item.public_dns_name }}"
            port: 22
            state: started
    loop: "{{ webb.instances }}"
 

- hosts: tag_name_web
  tasks:
       - name: roles executing
         include_role:
             name: httpdrole
       
- hosts: tag_name_lb
  tasks:
       - name: roles
         include_role: 
             name: mylb
